### ISSUE TITLE
打开阅读页面，出现一个椭圆形的背景，没有文字

### ISSUE THREAD

**Issue by lynn-long** [NoryCao/zhuishushenqi#3]
环境是xcode 9.2 ，iOS 11.2 iPhone8模拟器
源码build后，run
打开推荐列表，选择书籍“贴身校花”
出来的是一个椭圆形的背景，啥也没有，换源了就一直loading
![image](https://user-images.githubusercontent.com/3184009/34702691-1454b6a0-f52a-11e7-8a2a-eeee2fbe7f27.png)
点击字体变小，会是这样
![image](https://user-images.githubusercontent.com/3184009/34702713-367a96fa-f52a-11e7-9813-c6501b9215bb.png)

**Comment by NoryCao** [comment]
椭圆背景问题已修复，至于没有文字的问题，目前在iOS 11 上普遍存在，可用iOS 11以下版本测试。猜测可能是CoreText的绘制需要适配，这段时间比较忙，暂时没有时间适配，请谅解。

**Comment by lynn-long** [comment]
看起来是字体问题，我修复后提个pull request

**Comment by NoryCao** [comment]
好的
